language: php

sudo: required
php:
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
 - hhvm
 - nightly
 
before_script:
 - phpenv config-rm xdebug.ini
 - composer self-update
 - composer install
  
script:
  - phpunit CreateAccountTest.php
