language: php

sudo: required
php:
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
 - hhvm
 - nightly
 
env:
 - DB=mysql
 
before_script:
 - phpenv config-rm xdebug.ini
 - composer self-update
 - composer install
  
#phpunit --bootstrap src/autoload.php Tests/CreateAccountScriptTest
script:
  - phpunit CreateAccountScriptTest.php;
